# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
email: nahmed5150@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Graduate student in robotics at Northwestern University.
twitter_username: username
github_username: nahder
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5  # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
baseurl: ""  # No base path for GitHub Pages root

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Nader Ahmed"
  avatar : "/assets/images/nader.jpg"
  bio    : "M.S. in Robotics from Northwestern University. Currently looking for new opportunities!"
  links:
    - label: "Evanston, IL"
      icon: "fas fa-map-pin" 
      url: ""

    - label: "Email"
      icon: "fas fa-inbox"
      url: "mailto:nahmed5150@gmail.com"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nahder"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/naderahmed01/"


footer:
  links:
    - label: "Email"
      icon: "fas fa-inbox"
      url: "mailto:nahmed5150@gmail.com"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nahder"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/naderahmed01/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: projects
    values:
      layout: single

  - scope:
      path: ""
      type: manipulation_projects
    values:
      layout: single

  - scope:
      path: ""
      type: nav_projects
    values:
      layout: single

  - scope:
      path: ""
      type: turtlebot_projects
    values:
      layout: single

  - scope:
      path: ""
      type: vision_projects
    values:
      layout: single

collections:
  turtlebot_projects: 
    output: true 
    permalink: /:collection/:path/
  vision_projects: 
    output: true 
    permalink: /:collection/:path/  
  manipulation_projects: 
    output: true 
    permalink: /:collection/:path/
  nav_projects:
    output: true 
    permalink: /:collection/:path/
  projects:
    output: true 
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
